name: devoir1-ete435
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - shapely
  - numpy
  - pyproj
  - fiona
  - notebook
  - ipykernel
  - matplotlib
